services:
  app:
    container_name: agent-zero-cuda
    image: agent-zero-cuda
    build:
      dockerfile: dockerfile_nvidia
      context: .
      args:
        INSTALL_TYPE: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "55080:5000"
      - "55022:22"
      - "55510:55510"
    security_opt:
      - seccomp:unconfined
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - BASE_URL=http://localhost:5000
    volumes:
      - ./agent-zero-root:/root
