services:
  app:
    container_name: agent-zero-amd
    image: agent-zero-amd
    build:
      dockerfile: dockerfile_amd
      context: .
      args:
        INSTALL_TYPE: all
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    ports:
      - "55080:5000"
      - "55022:22"
    security_opt:
      - seccomp:unconfined
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - BASE_URL=http://localhost:5000
    volumes:
      - ./agent-zero-logs:/root/agent-zero/logs
      - ./agent-zero-config:/root/agent-zero/tmp
      - ./agent-zero-env/.env:/root/agent-zero/.env
